package de.tfr.slides.builders

import de.tfr.slides.builders.html.html


fun main() {
    println(theWorld())
    println(samplePage())
}

fun theWorld() = html {
    body {
        h1 { +"🗺 Die Welt" }
        p { +"Gondor" }
        p { +"Mordor" }
        p { +"Eriador" }
        a(href = "https://en.wikipedia.org/wiki/Minor_places_in_Middle-earth") {
            +"Middle Earth"
        }
    }
}

fun samplePage() =
    html {
        head {
            title { +"XML encoding with Kotlin" }
        }
        body {
            h1 { +"XML encoding with Kotlin" }
            p { +"this format can be used as an alternative markup to XML" }

            // an element with attributes and text content
            a(href = "http://kotlinlang.org") { +"Kotlin" }

            // mixed content
            p {
                +"This is some"
                b { +"mixed" }
                +"text. For more see the"
                a(href = "http://kotlinlang.org") { +"Kotlin" }
                +"project"
            }
            p { +"some text" }

            // content generated by
            for (i in 0..10)
                p { +"Line $i" }

        }
    }
